#!/usr/bin/env bash

if ! command -v mpv &>/dev/null; then
	echo "Error: mpv is not installed. Please install it before running this script."
	exit 1
fi

# should work unless the link has been changed/ended/taken down...
declare -A urls=(
	["study"]="https://youtu.be/jfKfPfyJRdk"
	["chill"]="https://youtu.be/rUxyKA_-grg"
	["game"]="https://youtu.be/MVPTGNGiI-4"
	["fcc"]="https://coderadio-relay-ffm.freecodecamp.org/radio/8010/radio.mp3"
)

declare -A messages=(
	["study"]="Playing lofi hip hop radio - beats to relax/study to"
	["chill"]="Playing lofi hip hop radio - beats to sleep/chill to"
	["game"]="Playing synthwave radio - beats to chill/game to"
	["fcc"]="Playing freeCodeCamp code Radio"
)

usage() {
	cat <<EOF
Usage: $(basename "$0") [OPTIONS]

Play/Stream lofi music audio, and nothing else
                          - Amberol (probably)

Options:
  -s, --study      Play lofi radio beats to relax/study music.
  -c, --chill      Play lofi radio beats sleeps/chill music.
  -g, --game       Play lofi synthwave radio beats to chill/game music.
  -f, --fcc        Play freeCodeCamp Code Radio.
  -r, --random     Play a random station url (study, chilll, game, fcc).
  -v, --video      Play with video (default: none, no video for fcc).
  -h, --help       Display this help message.
EOF
}

main() {
	local url
	local video=false
	# auto play if there's no arg provided based on time of the day
	if [[ $# -eq 0 ]]; then
		hour=$(date +%_H)
		if ((hour >= 22 && hour < 6)); then
			url=${urls["chill"]}
			station_name="chill"
		elif ((hour >= 6 && hour < 12)); then
			url=${urls["study"]}
			station_name="study"
		elif ((hour >= 18 && hour < 22)); then
			url=${urls["game"]}
			station_name="game"
		else
			url=${urls["fcc"]}
			station_name="fcc"
		fi
	else
		while [[ $# -gt 0 ]]; do
			case $1 in
			-s | --study | study)
				url=${urls["study"]}
				station_name="study"
				shift
				;;
			-c | --chill | chill)
				url=${urls["chill"]}
				station_name="chill"
				shift
				;;
			-g | --game | game)
				url=${urls["game"]}
				station_name="game"
				shift
				;;
			-f | --fcc | fcc)
				url=${urls["fcc"]}
				station_name="fcc"
				shift
				;;
			-r | --random)
				station_name=$(shuf -n 1 -e "${!urls[@]}")
				url=${urls[$station_name]}
				shift
				;;
			-v | --video)
				video=true
				shift
				;;
			-h | --help)
				usage
				exit 0
				;;
			*)
				echo "Unknown option: $1" >&2
				usage
				exit 1
				;;
			esac
		done
	fi

	echo "${messages[$station_name]}..."

	if $video; then
		mpv "$url"
	else
		mpv --no-video "$url"
	fi
}

main "$@"
