#!/usr/bin/env bash

if [ "$(uname -s)" == "Linux" ]; then
	NF_LS_DIR="$HOME/.cache/fzf/nf-ls"
elif [ "$(uname -s)" == "Darwin" ]; then
	NF_LS_DIR="$HOME/Library/Caches/fzf/nf-ls"
fi

get_nf_cheat_sheets() {
	glyphs=$(curl -s https://www.nerdfonts.com/cheat-sheet | awk '/const glyphs/,/}/' | sed '1d;$d;s/^[[:space:]]*//; s/"//g; s/,//g;')

	#Convert the glyphs code into icon
	while IFS=' ' read -r key code; do
		icon_code="\u$code"              # Create the Unicode string separately
		icon=$(printf "%b" "$icon_code") # Use printf with the -b option to interpret backslash escapes
		echo "$key: $icon"
	done <<<"$glyphs"
}

update_nf-ls_cache() {
	get_nf_cheat_sheets >"$NF_LS_DIR"/nf-ls-cheat.sh
}
export -f update_nf-ls_cache

if [ ! -d "$NF_LS_DIR" ]; then
	mkdir -p "$NF_LS_DIR"
	update_nf-ls_cache
fi

awk -F'::' '{print $2 "  --  " $1}' "$NF_LS_DIR"/nf-ls-cheat.sh | column -t |
	fzf -m \
		--header "Nerd Font Cheat.sh" \
		--bind "enter:execute(wl-copy {+1}; notify-send 'Nerd Font Cheat.sh' '{+1} {+3} - icon has been copied')" \
		--bind "del:execute(rm -rf $NF_LS_DIR)" \
		--bind "alt-u:execute(bash -c update_nf-ls_cache)" # this binding doesn't work
