#!/usr/bin/env bash

arp -a | awk '{gsub(/[()]/, ""); print NR ".", $1 " - " $2}' | column -t
read -rp "Choose device number: " choice

DEVICE_IP=$(arp -a | awk -v c="$choice" 'NR==c {gsub(/[()]/, ""); print $2}')

dynamic_port=$(nmap "$DEVICE_IP" -p 37000-44000 | awk -F"/" '/\/tcp/ {print $1}')
if [[ -n "$dynamic_port" ]]; then
	adb connect "$DEVICE_IP:$dynamic_port"
else
	adb connect "$DEVICE_IP:5555"
fi

scrcpy_flags=(
	"--window-borderless"
	"--turn-screen-off"
	"--show-touches"
	"--kill-adb-on-close"
)

if adb devices | grep -q "$DEVICE_IP"; then
	scrcpy "${scrcpy_flags[@]}" || { echo "Error: scrcpy is not installed" && exit 1; }
	# adb disconnect
else
	echo "Enable Wireless Debugging first and try again" && exit 1
fi
